# Generated by Django 5.1.1 on 2024-09-12 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ertelecom', '0003_alter_district_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='number',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='name',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nodes', to='ertelecom.city'),
        ),
        migrations.AlterField(
            model_name='house',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nodes', to='ertelecom.street'),
        ),
        migrations.AlterField(
            model_name='street',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nodes', to='ertelecom.district'),
        ),
    ]
