# Generated by Django 5.1.1 on 2024-09-13 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ertelecom', '0004_rename_name_city_label_rename_name_district_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='label',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='ertelecom.city'),
        ),
        migrations.AlterField(
            model_name='house',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='ertelecom.street'),
        ),
        migrations.AlterField(
            model_name='street',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='ertelecom.district'),
        ),
    ]
