# Generated by Django 5.1.1 on 2024-09-20 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ertelecom', '0007_alter_district_city_alter_house_street_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Название')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='ertelecom.house')),
            ],
            options={
                'verbose_name': 'Подъезд',
                'verbose_name_plural': 'Подъезды',
            },
        ),
    ]
